community/urls.py
from django.urls import path
from . import views

# Home app URL
urlpatterns = [
    path('', views.community, name='community'),
    path('<int:question_id>/', views.view_question, name='view_question'),

    # add, edit and delete questions urls
    path('ask/', views.add_question, name='ask'),
    path('edit/<int:question_id>/', views.edit_question, name='edit_question'),
    path('delete/<int:question_id>/', views.delete_question,
         name='delete_question'),

    # Add, edit and delete answers urls
    path('add_answer/<int:question_id>/', views.add_answer, name="add_answer"),
    path('edit_answer/<int:question_id>/<int:answer_id>/',
         views.edit_answer, name="edit_answer"),
    path('delete_answer/<int:question_id>/<int:answer_id>/',
         views.delete_answer, name="delete_answer"),
]

home/urls.py
from django.urls import path
from . import views

# Home app URL
urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('send/', views.send_contact_email, name='send'),
]

ur_gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # my created urls for the project
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('trolley/', include('trolley.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('community/', include('community.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom error handlers
handler404 = 'home.views.error_404_not_found'
handler500 = 'home.views.error_500_server_error'

community/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    """
    Below you will see the community question model
    for the community message board.
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question_title = models.CharField(max_length=250)
    question_message = models.TextField(max_length=1000)
    date_created = models.DateField(auto_now_add=True)
    time_created = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Answer(models.Model):
    """
    Below you will see the answer question model
    for the community message board.
    """
    id = models.AutoField(primary_key=True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_message = models.TextField(max_length=1000)
    date_created = models.DateField(auto_now_add=True)
    time_created = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

community/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    # Meta class is excluding specific fields but including the rest
    class Meta:
        model = Question
        exclude = ('user', 'date_created', 'time_created')

        # Setting the row attribute for the question message
        question_message = forms.CharField(widget=forms.Textarea
                                           (attrs={"rows": 3}),)

    def __init__(self, *args, **kwargs):
        """
        Adding placeholders and classes for question
        form fields, and remove auto-generated crispy form labels
        """
        super().__init__(*args, **kwargs)

        # Setting custom text placeholders
        placeholders = {
            'question_title': 'Question Title',
            'question_message': 'Type your question here',
        }

        # Attaching placeholders, setting class names and removing form labels
        for field in self.fields:
            placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[
                field].widget.attrs['class'] = 'rounded-0 question-form-fields'
            self.fields[field].label = False


class AnswerForm(forms.ModelForm):
    # Meta class is excluding specific fields but including the rest
    class Meta:
        model = Answer
        exclude = ('user', 'question', 'date_created', 'time_created')

    def __init__(self, *args, **kwargs):
        """
        Adding placeholders and classes for answer
        form field, and remove auto-generated crispy form labels
        """
        super().__init__(*args, **kwargs)

        # Setting custom text placeholders
        placeholders = {
            'answer_message': 'Type your answer here',
        }

        # Attaching placeholders, setting class names and removing form labels
        for field in self.fields:
            placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[
                field].widget.attrs['class'] = 'rounded-0 answer-form-fields'
            self.fields[field].label = False

community/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from .models import Question, Answer
from .forms import QuestionForm, AnswerForm

# This will stop non logged in users from gaining access
# to certain urls
from django.contrib.auth.decorators import login_required


def community(request):
    """
    This view returns the community home page
    """
    # Getting community questions and ordering by most recent
    questions = Question.objects.all().order_by(
        '-date_created', '-time_created')

    # context dictionary with keys and values to be
    # used in the rendered html template
    templates = 'community/community.html'
    context = {
        'questions': questions,
    }

    return render(request, templates, context)


@login_required
def view_question(request, question_id):
    """
    Viewing questions from the db
    """
    # Getting question using question id
    question = get_object_or_404(Question, pk=question_id)

    # Getting answers and filtering by question id and
    # ordering by new answers using date and time
    answers = Answer.objects.filter(
        question=question_id).order_by('-date_created', '-time_created')
    form = AnswerForm(request.POST)

    # context dictionary with keys and values to be
    # used in the rendered html template
    template = 'community/view_question.html'
    context = {
        'question': question,
        'answers': answers,
        'form': form,

    }

    return render(request, template, context)


@login_required
def add_question(request):
    """
    Adding a question to the db
    """
    # Checking if the request method is post for the form
    # which then checks to see if the form is valid, and
    # if so then save the form.
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.title = request.POST["question_title"]
            question.message = request.POST["question_message"]
            question.user = request.user
            question.save()
            # Message that will inform the user that the question they have
            # asked has been asked
            messages.success(
                request, f'Your question - {question.title}, has successfully\
                    been asked')
            return redirect(reverse('view_question', args=[question.id]))
        else:
            # Error message informing user that the question failed to ask
            messages.error(request, 'Question failed to ask,\
                Please make sure the form is correctly filled in.')
    else:
        form = QuestionForm()

    # context dictionary with keys and values to be
    # used in the rendered html template
    template = 'community/add_question.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_question(request, question_id):
    """A view to edit questions"""

    # Getting a question using question id
    question = get_object_or_404(Question, pk=question_id)

    # If that checks to see if the logged in user is the
    # user that has asked the question
    if not request.user == question.user:
        messages.warning(
            request, 'Only users that have asked the question, can edit')
        return redirect(reverse('community'))

    # Checking if request user, methods and form are post
    # and if they are then check if the form is valid, if so
    # then the form will save.
    if request.user == question.user:
        if request.method == "POST":
            form = QuestionForm(request.POST, instance=question)
            if form.is_valid():
                data = form.save(commit=False)
                data.save()
                # Message informing the user using toasts,
                # that there question has been updated and redirecting them.
                messages.success(request, 'Your question has been updated')
                return redirect(reverse('view_question', args=[question.id]))
            else:
                # Error message if question fails to update and
                # then redirecting them
                messages.error(
                    request, 'Failed to update question.\
                        Please ensure the form is valid.')
                return redirect(reverse('view_question', args=[question.id]))
        else:
            form = QuestionForm(instance=question)

        # context dictionary with keys and values to be
        # used in the rendered html template
        template = 'community/edit_question.html'
        context = {
            'form': form,
        }
        return render(request, template, context)
    else:
        return redirect(reverse('view_question', args=[question.id]))


@login_required
def delete_question(request, question_id):
    """
    Delete a current question in the db
    """

    # Getting question using question id
    question = get_object_or_404(Question, pk=question_id)

    # If that checks to see if the logged in user is the
    # user that has asked the question
    if not request.user == question.user:
        messages.warning(
            request, 'Only users that have asked the question, can delete')
        return redirect(reverse('community'))

    # Deleting question
    question.delete()
    # Success message to user using toasts informing them that the question
    # has been deleted and redirecting them back to the community page.
    messages.success(
        request, f'Your question - {question.question_title}\
            has been successfully deleted')

    return redirect(reverse('community'))


@login_required
def add_answer(request, question_id):
    """ Adding an answer to a question """
    # Getting question
    question = get_object_or_404(Question, pk=question_id)

    # Checking if request is post and form is post and if it is
    # check if the form is valid and then save the form.
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.message = request.POST["answer_message"]
            data.user = request.user
            data.question = question
            data.save()
            # Message informing the user using toasts,
            # that there answer has been added and redirecting them.
            messages.success(request, 'Thank you for leaving an answer')
            return redirect(reverse('view_question', args=[question.id]))
        else:
            # Error message if answer fails to add
            messages.error(
                request, 'Failed to add your answer.')
    else:

        form = AnswerForm()

    # context dictionary with keys and values to be
    # used in the rendered html template
    template = 'community/includes/add_answer.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_answer(request, question_id, answer_id):
    """A view to edit an answer"""
    # Getting both questions and answers
    question = get_object_or_404(Question, pk=question_id)
    answer = get_object_or_404(Answer, question=question, pk=answer_id)

    # If that checks to see if the logged in user is the
    # user that has asked the question
    if not request.user == answer.user:
        messages.warning(
            request, 'Only users that have answered the question, can edit')
        return redirect(reverse('community'))

    # Checking if request user and methods are post and form is post
    # and if they are then check if the form is valid and then save the form.
    if request.user == answer.user:
        if request.method == "POST":
            form = AnswerForm(request.POST, instance=answer)
            if form.is_valid():
                data = form.save(commit=False)
                data.save()
                # Message informing the user using toasts,
                # that there answer has been updated and redirecting them.
                messages.success(request, 'Your answer has been updated')
                return redirect(reverse('view_question', args=[question.id]))
            else:
                # Error message if answer fails to update and redirecting them
                messages.error(
                    request, 'Failed to update answer.\
                        Please ensure the form is valid.')
                return redirect(reverse('view_question', args=[question.id]))
        else:
            form = AnswerForm(instance=answer)

        # context dictionary with keys and values to be
        # used in the rendered html template
        template = 'community/edit_answer.html'
        context = {
            'form': form,
        }
        return render(request, template, context)
    else:
        return redirect(reverse('view_question', args=[question.id]))


@login_required
def delete_answer(request, question_id, answer_id):
    """A view to delete an answer"""
    # Getting both questions and answers
    question = get_object_or_404(Question, pk=question_id)
    answer = get_object_or_404(Answer, question=question, pk=answer_id)

    # If that checks to see if the logged in user is the
    # user that has asked the question
    if not request.user == answer.user:
        messages.warning(
            request, 'Only users that have answered the question, can delete')
        return redirect(reverse('community'))

    # Checking if the user logged in is the user that left the answer
    # and if true then the answer will be deleted.
    if request.user == answer.user:
        answer.delete()
        # Message using toasts to inform user that they
        # have deleted there answer
        messages.success(request, 'Your answer has successfully been deleted')

    return redirect(reverse('view_question', args=[question.id]))

community/templates/community/add_question.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar -->
<div class="container top-head-container" id="top-head-con">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Ask a question container -->
<div class="container">
    <div class="row">
        <!-- Ask a question page heading -->
        <div class="col text-center mt-5 mt-lg-4">
            <h2 class="custom-font-head fw-bold text-uppercase ts-4 mt-5 my-lg-4">Ask A Question</h2>
            <hr class="w-50 mx-auto">
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 col-lg-6 mx-auto">
            <!-- Ask a question form -->
            <form action="{% url 'ask' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <!-- Question Crispy form -->
                    <div class="col-12">
                        {{ form | crispy }}
                    </div>
                </div>

                <!-- Form submit button -->
                <div class="text-center float-lg-end">
                <a href="{% url 'community' %}" class="btn btn-outline-dark rounded-0">Go Back</a>
                <input type="submit" class="btn btn-dark custom-bg rounded-0"
                    value="Ask Question">
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/ask_question.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar -->
<div class="container top-head-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Ask a question container -->
<div class="container">
    <div class="row">
        <!-- Ask a question page heading -->
        <div class="col text-center mt-5 mt-lg-4">
            <h2 class="custom-font-head fw-bold text-uppercase text-spacing mt-5 my-lg-4">Ask A Question</h2>
            <hr class="w-50 mx-auto">
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 col-lg-6 mx-auto">
            <!-- Ask a question form -->
            <form action="{% url 'ask' %}" method="POST">
                {% csrf_token %}
                <div class="row">
                    <!-- Question Crispy form -->
                    <div class="col-12">
                        {{ form | crispy }}
                    </div>
                </div>

                <!-- Form submit button -->
                <input type="submit" class="btn btn-dark custom-bg rounded-0 float-lg-end d-block mx-auto mx-lg-0 mb-4"
                    value="Ask Question">
            </form>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/community.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar  -->
<div class="container top-head-container" id="top-head-con">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Main community container -->
<div class="container community-con">
    <div class="row">
        <div class="col text-center">
            <!-- Community header with horizontal rule -->
            <h2 class="custom-font-head fw-bold text-capitalize ts-4 mt-5 mt-lg-4 mb-2">Welcome to the UR-GYM
                community ({{ questions.count}})</h2>
            <hr>
        </div>
    </div>
    <!-- Community rules -->
    <div class="row">
        <div class="col text-center">
            <p class="ts-1 fs-4 mb-1"><strong>Please follow these simple rules:</strong><br>
                <span class="text-danger fs-5">No Bullying, No Swearing, No Racism</span></p>
            <p class="ts-1 fw-bold">If anyone is caught breaking these rules, they will be instantly banned from the site.</p>
            <a href="{% url 'home' %}" class="btn btn-outline-dark rounded-0 mt-3">Go Back</a>
            <a href="{% url 'ask' %}" class="edit-question btn px-4 rounded-0 btn-dark custom-bg mt-3">Ask A Question</a>
        </div>
    </div>
    <!-- Community messages -->
    <div class="container">
        <!-- Django for loop, iterating through the questions model -->
        {% for question in questions %}
        <div class="row mt-4 mb-4 justify-content-center">
            <!-- Left question column -->
            <div class="col-12 col-lg-4 text-center custom-bg-2 p-3">
                <div><strong>Username: </strong>{{ question.user}}</div>
                <div><strong>Date: </strong>{{ question.date_created}}</div>
                <div><strong>Time: </strong>{{ question.time_created}}</div>

                <!-- Django if checking to check to see if the user logged in is the same
                user that left the review and if it is then it will display the edit and delete button -->
                {% if request.user == question.user %}
                <div class="row mt-3">
                    <div class="col text-center">
                        <!-- Edit and delete buttons for user who have asked a question -->
                        <a href="{% url 'edit_question' question.id %}"
                            class="edit-question btn btn-sm px-3 rounded-0 btn-secondary">Edit</a>
                        <a href="{% url 'delete_question' question.id %}"
                            class="delete-question btn btn-sm rounded-0 btn-secondary">Delete</a>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Right question column -->
            <div class="col-12 col-lg-6 text-center border border-outline p-3">
                <div class="fw-bold pb-2">{{ question.question_title}}</div>
                <div>{{ question.question_message|truncatechars:100 }}</div>
                <a href="{% url 'view_question' question.id %}"
                class="read-more btn btn-sm rounded-0 btn-secondary mt-3">Read More</a>
            </div>
        </div>
        <hr class="w-75 mx-auto">
        {% endfor %}
    </div>

</div>
{% endblock %}

community/templates/community/edit_answer.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar -->
<div class="container top-head-container" id="top-head-con">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Edit a answer container -->
<div class="container">
    <div class="row">
        <!-- Edit a answer page heading -->
        <div class="col text-center mt-5 mt-lg-4">
            <h2 class="custom-font-head fw-bold text-uppercase ts-4 mt-5 my-lg-4">Edit A Answer</h2>
            <hr class="w-50 mx-auto">
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 col-lg-6 mx-auto">
            <!-- Edit a answer form -->
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <!-- Answer Crispy form -->
                    <div class="col-12">
                        {{ form | crispy }}
                    </div>
                </div>

                <!-- Form submit button -->
                <a href="{% url 'community' %}" class="btn btn-outline-dark rounded-0">Go Back</a>
                <input type="submit" class="btn btn-dark custom-bg rounded-0 float-lg-end d-block mx-auto mx-lg-0 mb-4"
                    value="Update Answer">
            </form>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/edit_question.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar -->
<div class="container top-head-container" id="top-head-con">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- Edit a question container -->
<div class="container">
    <div class="row">
        <!-- Edit a question page heading -->
        <div class="col text-center mt-5 mt-lg-4">
            <h2 class="custom-font-head fw-bold text-uppercase ts-4 mt-5 my-lg-4">Edit A Question</h2>
            <hr class="w-50 mx-auto">
        </div>
    </div>

    <div class="row">
        <div class="col-12 col-md-8 col-lg-6 mx-auto">
            <!-- Edit a question form -->
            <form action="" method="POST">
                {% csrf_token %}
                <div class="row">
                    <!-- Question Crispy form -->
                    <div class="col-12">
                        {{ form | crispy }}
                    </div>
                </div>

                <!-- Form submit button -->
                <div class="text-center float-lg-end">
                    <a href="{% url 'community' %}" class="btn btn-outline-dark rounded-0">Go Back</a>
                    <input type="submit" class="btn btn-dark custom-bg rounded-0"
                        value="Update Question">
                    </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

community/templates/community/view_question.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
<!-- This is needed to push the content down under the navigation bar -->
<div class="container top-head-container" id="top-head-con">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<!-- View a question container -->
<div class="container">
    <div class="row">
        <!-- View a question page heading -->
        <div class="col text-center mt-5 mt-lg-4">
            <h2 class="custom-font-head fw-bold text-uppercase ts-4 mt-3 mt-lg-4">{{ question.question_title }}
            </h2>
            <hr class="w-50 mx-auto">
        </div>
    </div>
    <!-- View question info -->
    <div class="row">
        <!-- Username -->
        <div class="col-12 col-md-3 text-muted text-center text-lg-end d-none d-md-block"><strong>Asked by:</strong><br>
            {{ question.user }}</div>
        <div class="col-12 col-md-3 text-muted text-center text-lg-end d-block d-md-none"><strong>Asked by:</strong>
            {{ question.user }}</div>

        <!-- Date -->
        <div class="col-12 col-md-3 text-muted text-center text-lg-center my-2 my-md-0 d-none d-md-block">
            <strong>Date:</strong><br> {{ question.date_created }}</div>
        <div class="col-12 col-md-3 text-muted text-center text-lg-center my-2 my-md-0 d-block d-md-none">
            <strong>Date:</strong> {{ question.date_created }}</div>

        <!-- Time -->
        <div class="col-12 col-md-3 text-muted text-center text-lg-center mb-2 d-none d-md-block"><strong>Time:</strong><br>
            {{ question.time_created }}</div>
        <div class="col-12 col-md-3 text-muted text-center text-lg-center mb-2 d-block d-md-none"><strong>Time:</strong>
            {{ question.time_created }}</div>

        <!-- Answers -->
        <div class="col-12 col-md-3 text-muted text-center text-lg-start d-none d-md-block">
            <strong>Answers:</strong><br>
            {{ answers.count }}</div>
        <div class="col-12 col-md-3 text-muted text-center text-lg-start d-block d-md-none"><strong>Answers:</strong>
            {{ answers.count }}</div>

        <!-- if the  user logged in is the user that asked the question, then that user will
        be able to edit and delete there question -->
        {% if request.user == question.user %}
        <div class="row mt-3 mx-auto">
            <div class="col text-center">
                <!-- Edit and delete buttons for user who have asked a question -->
                <a href="{% url 'edit_question' question.id %}"
                    class="edit-question btn btn-sm px-3 rounded-0 btn-secondary">Edit</a>
                <a href="{% url 'delete_question' question.id %}"
                    class="delete-question btn btn-sm rounded-0 btn-secondary">Delete</a>
            </div>
        </div>
        {% endif %}

        <hr class="w-50 mx-auto my-3">
    </div>
    <!-- View question info -->
    <div class="row">
        <div class="col-12 col-lg-8 mx-auto">
            <div class="text-center fs-5 ts-1">
                <p>{{ question.question_message }}</p>
            </div>
        </div>
    </div>
    <!-- Answers to questions -->
    <div class="answer-container">
        <div class="row text-center">
            <!-- Answer heading with answer count -->
            <h3 class="custom-font-head text-uppercase fw-bold product-head mt-lg-5 mb-2">Answers ({{answers.count}})</h3>
            <!-- Answer include from includes dir -->
            {% include "community/includes/answers.html" %}
            <!-- Add answer form include from includes dir -->
            {% include "community/includes/add_answer.html" %}
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
<!-- This is to remove the class called is-invalid from the answer message textarea
which was causing validation to show up all the time, even when the form was not filled in -->
<script type="text/javascript">
    $(document).ready(function () {
        $('.answer-form-fields').removeClass('is-invalid');
        $("#id_answer_message").attr({"row" : 3});
    });
</script>
{% include 'products/includes/qty_input_btn_script.html' %}
{% endblock %}